FROM ruby:3.2-alpine

RUN apk add --no-cache build-base git

WORKDIR /srv/jekyll

COPY Gemfile* ./
RUN bundle install

EXPOSE 4000

CMD ["bundle", "exec", "jekyll", "serve", "-s", "docs", "--host", "0.0.0.0", "--force_polling"]
