[package]
name = "trellis-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["png", "diagnostics"]
png = ["dep:resvg"]
diagnostics = []

[dependencies]
trellis-parser = { path = "../trellis-parser" }
serde = { workspace = true }
serde_json = { workspace = true }
resvg = { workspace = true, optional = true }

[dev-dependencies]
