[package]
name = "trellis-wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
trellis-parser = { path = "../trellis-parser" }
# Disable the `png` feature: resvg does not compile for wasm32-unknown-unknown
trellis-core = { path = "../trellis-core", default-features = false }
wasm-bindgen = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
