[package]
name = "trellis-validate"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
trellis-parser = { path = "../trellis-parser" }
trellis-core = { path = "../trellis-core" }
serde = { workspace = true }
serde_json = { workspace = true }
